language: r
sudo: required
warnings_are_errors: true

os:
  - linux
  - osx

before_install:
  - echo "options(repos = c(CRAN='https://cran.rstudio.com/'))" > ~/.Rprofile

apt_packages:
  - libgsl0-dev

brew_packages:
  - gsl

r_packages:
  - covr

after_failure:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cat /home/travis/build/ropensci/git2r/git2r.Rcheck/00install.out; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cat /Users/travis/build/ropensci/git2r/git2r.Rcheck/00install.out; fi

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'library(covr); coveralls()'; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cat /home/travis/build/ropensci/git2r/git2r.Rcheck/00install.out; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cat /Users/travis/build/ropensci/git2r/git2r.Rcheck/00install.out; fi

notifications:
  email:
    on_success: change
    on_failure: change
