# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libgsl0-dev

matrix:
  include:
    - r: 3.1
    - r: 3.2
    - r: 3.3
    - r: 3.4
    - r: oldrel
    - r: release
      r_packages: covr
      r_github_packages: jimhester/lintr
      after_success:
        - Rscript -e "covr::coveralls()"
        - R CMD INSTALL $PKG_TARBALL
        - Rscript -e "lintr::lint_package(linters = lintr::with_defaults(object_name_linter = NULL, object_usage_linter = NULL))"
    - r: devel
    - os: osx
      brew_packages: gsl

after_failure:
  - cat "${RCHECK_DIR}/00install.out"

after_success:
  - cat "${RCHECK_DIR}/00install.out"

notifications:
  email:
    on_success: change
    on_failure: change
