trigger:
- master

jobs:
- job: ubuntu_R_3_3
  displayName: "Linux, R-3.3"
  pool:
    vmImage: "Ubuntu-18.04"
  steps:
  - template: azure-pipelines/ubuntu-install-R-3_3.yml
  - bash: |
      cd
      echo 'options(repos = "https://cloud.r-project.org")' > .Rprofile
      echo 'R_LIBS_USER="$(Agent.BuildDirectory)/R/library"' > .Renviron
      mkdir -p $(Agent.BuildDirectory)/R/library
    displayName: "Customize R startup"
  - template: azure-pipelines/R-sessioninfo.yml
  - bash: |
      sudo apt-get -y install libgsl0-dev
      Rscript -e "install.packages('digest')"
    displayName: "Install package dependencies"
  - template: azure-pipelines/build-package.yml
  - template: azure-pipelines/check-package.yml

- job: ubuntu_R_3_4
  displayName: "Linux, R-3.4"
  pool:
    vmImage: "Ubuntu-18.04"
  steps:
  - template: azure-pipelines/ubuntu-install-R-3_4.yml
  - bash: |
      cd
      echo 'options(repos = "https://cloud.r-project.org")' > .Rprofile
      echo 'R_LIBS_USER="$(Agent.BuildDirectory)/R/library"' > .Renviron
      mkdir -p $(Agent.BuildDirectory)/R/library
    displayName: "Customize R startup"
  - template: azure-pipelines/R-sessioninfo.yml
  - bash: |
      sudo apt-get -y install libgsl0-dev
      Rscript -e "install.packages('digest')"
    displayName: "Install package dependencies"
  - template: azure-pipelines/build-package.yml
  - template: azure-pipelines/check-package.yml

- job: ubuntu_R_3_5
  displayName: "Linux, R-3.5"
  pool:
    vmImage: "Ubuntu-18.04"
  steps:
  - template: azure-pipelines/ubuntu-install-R-3_5.yml
  - bash: |
      cd
      echo 'options(repos = "https://cloud.r-project.org")' > .Rprofile
      echo 'R_LIBS_USER="$(Agent.BuildDirectory)/R/library"' > .Renviron
      mkdir -p $(Agent.BuildDirectory)/R/library
    displayName: "Customize R startup"
  - template: azure-pipelines/R-sessioninfo.yml
  - bash: |
      sudo apt-get -y install libgsl0-dev
      Rscript -e "install.packages('digest')"
    displayName: "Install package dependencies"
  - template: azure-pipelines/build-package.yml
  - template: azure-pipelines/check-package.yml

- job: fedora_R_release
  displayName: "Linux, R-release"
  pool:
    vmImage: "Ubuntu-latest"
  container: fedora:latest
  steps:
  - template: azure-pipelines/dnf-install-R-release.yml
  - template: azure-pipelines/customize-R-startup.yml
  - template: azure-pipelines/R-sessioninfo.yml
  - bash: |
      sudo dnf -y install gsl-devel
      Rscript -e "install.packages('digest')"
    displayName: "Install package dependencies"
  - template: azure-pipelines/build-package.yml
  - template: azure-pipelines/check-package.yml
  - template: azure-pipelines/static-code-analysis.yml
  - bash: |
      cd ..
      nm -g SimInf.Rcheck/SimInf/libs/SimInf.so | \
        grep -c " T " | grep 1 && exit 0 || exit 1
    displayName: "Check visibility of C entry points"
  - template: azure-pipelines/code-coverage.yml
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: sdk
      version: 2.2.207
      installationPath: $(Agent.ToolsDirectory)/dotnet
    displayName: "Install dotnet core"
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'coverage.xml'

- job: fedora_R_devel_gcc
  displayName: "Linux, R-devel, GCC"
  pool:
    vmImage: "Ubuntu-latest"
  container: fedora:latest
  steps:
  - template: azure-pipelines/dnf-install-R-devel.yml
  - template: azure-pipelines/customize-R-startup.yml
  - template: azure-pipelines/R-sessioninfo.yml
  - bash: |
      sudo dnf -y install gsl-devel
      Rscript -e "install.packages('digest')"
    displayName: "Install package dependencies"
  - template: azure-pipelines/build-package.yml
  - template: azure-pipelines/check-package.yml

- job: macosx_R_release
  displayName: "Mac OS X, R-release"
  pool:
    vmImage: "macOS-latest"
  steps:
  - template: azure-pipelines/macos-install-R-release.yml
  - template: azure-pipelines/macos-cusomize-R-startup.yml
  - template: azure-pipelines/R-sessioninfo.yml
  - bash: |
      brew update
      brew reinstall llvm
      brew install gsl
      Rscript -e "install.packages('digest')"
    displayName: "Install package dependencies"
  - template: azure-pipelines/build-package.yml
  - template: azure-pipelines/check-package.yml
  - bash: |
      cd ..
      cat *.Rcheck/00install.out
    displayName: "Output the installation log"
  - bash: |
      cd ..
      cat SimInf.Rcheck/00_pkg_src/SimInf/config.log
    displayName: "Output the configuration log"

- job: macosx_R_devel
  displayName: "Mac OS X, R-devel"
  pool:
    vmImage: "macOS-latest"
  steps:
  - template: azure-pipelines/macos-install-R-devel.yml
  - template: azure-pipelines/macos-cusomize-R-startup.yml
  - template: azure-pipelines/R-sessioninfo.yml
  - bash: |
      brew update
      brew reinstall llvm
      brew install gsl
      Rscript -e "install.packages('digest')"
    displayName: "Install package dependencies"
  - template: azure-pipelines/build-package.yml
  - template: azure-pipelines/check-package.yml
  - bash: |
      cd ..
      cat *.Rcheck/00install.out
    displayName: "Output the installation log"
  - bash: |
      cd ..
      cat SimInf.Rcheck/00_pkg_src/SimInf/config.log
    displayName: "Output the configuration log"
