trigger:
- master

jobs:
- job: fedora_R_release_gcc
  displayName: "Fedora, R-release, GCC"
  pool:
    vmImage: 'Ubuntu-latest'
  container: fedora:latest
  steps:
  - template: azure-pipelines/dnf-install-R.yml
  - bash: |
      sudo dnf -y install gsl-devel
    displayName: 'Install package dependencies'
  - template: azure-pipelines/build-package.yml
  - template: azure-pipelines/check-package.yml
