name: R-CI

on:
  push:
  pull_request:

jobs:
  R-CI:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - uses: actions/checkout@v3

      - name: Install R
        run: sudo dnf --assumeyes install langpacks-en R

      - name: Setup to install binary R packages
        run: |
          sudo dnf --assumeyes install "dnf-command(copr)"
          sudo dnf --assumeyes copr enable iucar/cran

      - name: Install package dependencies
        run: >
          sudo dnf --assumeyes install
          devscripts-checkbashisms
          gsl-devel
          R-CRAN-digest
          R-CRAN-knitr
          R-CRAN-rmarkdown

      - name: R session information
        run: Rscript -e "sessionInfo()"

      - name: Build package
        run: R CMD build --no-manual .

      - name: Check package
        run: |
          _R_CHECK_CRAN_INCOMING_=FALSE R CMD check --no-stop-on-test-error --as-cran $(ls -1t *.tar.gz | head -n 1)
          if grep -q WARNING SimInf.Rcheck/00check.log; then exit 1; fi
