name: R-CI

on:
  push:
  pull_request:

jobs:
  R-CI:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - uses: actions/checkout@v3

      - name: Install R and required software
        run: >
          sudo dnf --assumeyes install
          clang-analyzer
          cppcheck
          devscripts-checkbashisms
          langpacks-en
          R
          tidy

      - name: Setup Copr to install binary R packages
        run: |
          sudo dnf --assumeyes install "dnf-command(copr)"
          sudo dnf --assumeyes copr enable iucar/cran

      - name:  Determine package name and version from DESCRIPTION file
        run: |
          echo "PKG_NAME=$(grep -i ^package DESCRIPTION | cut -d : -d ' ' -f 2 | tr -d '\r')" >> $GITHUB_ENV
          echo "PKG_VERSION=$(grep -i ^version DESCRIPTION | cut -d : -d ' ' -f 2 | tr -d '\r')" >> $GITHUB_ENV

      - name: Name of built package
        run: echo "PKG_TAR=${{ env.PKG_NAME }}_${{ env.PKG_VERSION }}.tar.gz" >> $GITHUB_ENV

      - name: Install package dependencies
        run: >
          sudo dnf --assumeyes install
          gsl-devel
          R-CRAN-digest
          R-CRAN-knitr
          R-CRAN-lintr
          R-CRAN-rmarkdown

      - name: R session information
        run: Rscript -e "sessionInfo()"

      - name: Build package
        run: R CMD build --no-manual --compact-vignettes=both .

      - name: Check package
        run: |
          _R_CHECK_CRAN_INCOMING_=FALSE R CMD check --no-stop-on-test-error --as-cran ${{ env.PKG_TAR }}
          if grep -q WARNING ${{ env.PKG_NAME }}.Rcheck/00check.log; then exit 1; fi

      - name: Static code analysis of R code using lintr
        run: Rscript -e "library(lintr); l <- lint_package(); print(l); quit(save = 'no', status = length(l) > 0)"

      - name: Static code analysis of C code using cppcheck
        run: |
          cppcheck --enable=warning,style,performance,portability --inline-suppr --quiet --verbose src > ${{ env.PKG_NAME }}.Rcheck/00cppcheck.log 2>&1
          cat ${{ env.PKG_NAME }}.Rcheck/00cppcheck.log
          if [[ -s ${{ env.PKG_NAME }}.Rcheck/00cppcheck.log ]]; then exit 1; fi

      - name: Static code analysis of C code using scan-build
        run: |
          scan-build make -f <(echo -e "install:\n\tR CMD INSTALL ${{ env.PKG_TAR }}") > ${{ env.PKG_NAME }}.Rcheck/00scan-build.log 2>&1
          cat ${{ env.PKG_NAME }}.Rcheck/00scan-build.log
