name: R-CI

on:
  push:
  pull_request:

jobs:
  R-CI:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - uses: actions/checkout@v3

      - name: Install R
        run: sudo dnf --assumeyes install langpacks-en R

      - name: Setup to install binary R packages
        run: |
            sudo dnf --assumeyes install "dnf-command(copr)"
            sudo dnf --assumeyes copr enable iucar/cran
            sudo dnf --assumeyes install R-CoprManager

      - name: Install package dependencies
        run: |
            sudo dnf --assumeyes install gsl-devel
            Rscript -e "install.packages(c('digest', 'knitr', 'rmarkdown'))"

      - name: R session information
        run: Rscript -e "sessionInfo()"

      - name: Build package
        run: R CMD build --no-manual .
