steps:
- bash: |
    cd ..
    _R_CHECK_CRAN_INCOMING_=FALSE R CMD check \
      --no-stop-on-test-error \
      --as-cran \
      *.tar.gz
  displayName: 'Check package'

- bash: |
    cd ..
    cat *.Rcheck/00check.log
    cat *.Rcheck/00install.out
  condition: always()
  displayName: 'Output the package check log'
