steps:
- bash: |
    cd
    sudo dnf -y install \
      langpacks-en \
      libcurl-devel \
      libX11-devel \
      libXt-devel \
      R \
      readline-devel
    curl https://stat.ethz.ch/R/daily/R-devel.tar.gz -o R-devel.tar.gz
    tar xf R-devel.tar.gz
    cd R-devel
    ./configure
    make
    sudo make install
  displayName: "Install R-devel"
