variables:
  R_LIBS_SITE: '/usr/share/R/library'
  R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
  CRAN: 'https://cloud.r-project.org'

steps:
- bash: |
    sudo dnf -y install langpacks-en R
  displayName: "Install R"

- bash: |
    cd
    echo 'options(repos = "$(CRAN)")' > .Rprofile
    echo 'Sys.setlocale("LC_CTYPE", "en_US.UTF-8")' >> .Rprofile
    echo 'Sys.setlocale("LC_TIME", "en_US.UTF-8")' >> .Rprofile
    echo 'Sys.setlocale("LC_COLLATE", "en_US.UTF-8")' >> .Rprofile
    echo 'Sys.setlocale("LC_MONETARY", "en_US.UTF-8")' >> .Rprofile
    echo 'Sys.setlocale("LC_MESSAGES", "en_US.UTF-8")' >> .Rprofile
    echo 'Sys.setlocale("LC_PAPER", "en_US.UTF-8")' >> .Rprofile
    echo 'Sys.setlocale("LC_MEASUREMENT", "en_US.UTF-8")' >> .Rprofile
    echo 'R_LIBS_SITE="$(R_LIBS_SITE)"' > .Renviron
    echo 'R_LIBS_USER="$(R_LIBS_USER)"' >> .Renviron
    mkdir -p $(R_LIBS_USER)
  displayName: "Customize R startup"

- bash: |
    Rscript -e "sessionInfo()"
  displayName: 'R session information'
