steps:
- bash: |
    cd
    echo 'options(repos = "https://cloud.r-project.org")' > .Rprofile
    echo 'Sys.setenv(PATH = paste0("/usr/texbin:/Library/TeX/texbin:", Sys.getenv("PATH")))' >> .Rprofile
    echo 'R_LIBS_USER="$(Agent.BuildDirectory)/R/library"' > .Renviron
    mkdir .R
    echo 'CC=/usr/local/opt/llvm/bin/clang' > .R/Makevars
    echo 'CXX=/usr/local/opt/llvm/bin/clang++' >> .R/Makevars
    echo 'LDFLAGS=-L/usr/local/opt/llvm/lib' >> .R/Makevars
    mkdir -p $(Agent.BuildDirectory)/R/library
  displayName: "Customize R startup"
