steps:
- bash: |
    cd ..
    cat *.Rcheck/00install.out
  displayName: "Output the installation log"
- bash: |
    cd ..
    cat SimInf.Rcheck/00_pkg_src/SimInf/config.log
  displayName: "Output the configuration log"
